[package]
name = "relm_process_events"
version = "0.1.0"
authors = ["Emmanuel Touzery <etouzery@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relm = "0.21.0"
gtk = "0.9.2"
relm-derive = "0.21.0"
